#转义字符
print('hello\nworld')#n-->newline表示换行
print('hello\tworld')
print('helloooo\tworld')
print('hello\rworld')#world将hello进行了覆盖
print('hello\bworld')#\b是退一个格，将o退没了
print('http:\\www.baidu.com')
print('http:\\\\www.baidu.com')
print('老师说:\'大家好\'')
#原字符：不希望字符串中的转义字符起作用，就使用转义字符，即在字符串之前加上r，或R
print(r'hello\nworld')
#最后一个字符不能是反斜杠，但是可以是两个反斜杠
#print(r'hello\nworld\')
print(r'hello\nworld\\')
#变量定义与使用
name='玛丽亚'
print(name)
print('标识',id(name))
print('类型',type(name))
print('值',name)
#进制数，分为二进制（0b开头）、十进制、八进制（0o开头）、十六进制（0x开头）
#浮点数
n1=1.1
n2=2.2
n3=2.1
print(n1+n2)
print(n1+n3)
from decimal import Decimal
print(Decimal('1.1')+Decimal('2.2'))
#布尔值可以转成整数运算
f1=True
f2=False
print(f1+1)
print(f2+1)
#数据类型转换
name='张三'
age=20
#print('我叫'+name+'今年，'+age+'几岁')
print('我叫'+name+',今年'+str(age)+'岁')#当str类型与int类型进行连接时，报错，应该进行类型转换
